name: Build and Push ES

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: build 
          
      - name: Install dependencies and build
        run: |
          npm install
          npm run crowdin:download
          npm run build
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          API_TOKEN_ENV: ${{ secrets.API_TOKEN_ENV }}
          API_TOKEN: ${{ secrets.API_TOKEN_ENV }}

      - name: Commit build
        run: |
          git config --local user.email "builder@example.com"
          git config --local user.name "Builder"
          git add -f ./build
          git commit -m "Add build" 

      - name: Push to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          repository: matiasbenary/testdocusaurus
